### ISSUE TITLE
Qiitaに公開する件について

### ISSUE THREAD

**Issue by 1gu** [1gu/www-textbook#14]
ひとまずHTMLに関するドキュメントがある程度溜まってきたので一旦Qiita上で公開し、こちらのリポジトリが更新され次第、適宜Qiitaの記事の更新もやっていこうかと思うのですがどうでしょうか？

**Comment by nnsnodnb** [comment]
@1gu :+1:

**Comment by NKMR6194** [comment]
公開してしまって良いと思います。

ただ、玄人にツッコまれそうな点がいくつかあったので、プルリク#15 の確認お願いします

**Comment by 1gu** [comment]
#15 :+1:
 ありがとうございます

**Comment by NKMR6194** [comment]
@1gu :smile:

**Comment by 1gu** [comment]
http://qiita.com/iguchi1124/items/552841858c495e23dfc8 遅くなりましたが一旦公開しました！皆様有難うございます。何か問題がありましたらissue立てるか編集リクエスト下さい。
